// Auto-generated WC 2026 squad data
export interface Player { name: string; position: string; number?: number }
export const WC_SQUADS: Record<string, Player[]> = {
  'Mexico': [
    { name: 'C. Acevedo', position: 'Goalkeeper', number: 12 },
    { name: 'G. Ochoa', position: 'Goalkeeper', number: 13 },
    { name: 'J. Rangel', position: 'Goalkeeper', number: 1 },
    { name: 'J. Gallardo', position: 'Defender', number: 23 },
    { name: 'C. Montes', position: 'Defender', number: 3 },
    { name: 'I. Reyes', position: 'Defender', number: 15 },
    { name: 'J. Sánchez', position: 'Defender', number: 2 },
    { name: 'J. Vásquez', position: 'Defender', number: 5 },
    { name: 'E. Álvarez', position: 'Midfielder', number: 4 },
    { name: 'M. Chávez', position: 'Defender', number: 20 },
    { name: 'O. Vargas', position: 'Midfielder', number: 18 },
    { name: 'L. Chávez', position: 'Midfielder', number: 24 },
    { name: 'Álvaro Fidalgo', position: 'Midfielder', number: 8 },
    { name: 'B. Gutiérrez', position: 'Midfielder', number: 26 },
    { name: 'É. Lira', position: 'Midfielder', number: 6 },
    { name: 'G. Mora', position: 'Midfielder', number: 19 },
    { name: 'O. Pineda', position: 'Midfielder', number: 17 },
    { name: 'L. Romo', position: 'Midfielder', number: 7 },
    { name: 'R. Alvarado', position: 'Midfielder', number: 25 },
    { name: 'S. Giménez', position: 'Attacker', number: 11 },
    { name: 'A. González', position: 'Attacker', number: 14 },
    { name: 'C. Huerta', position: 'Midfielder', number: 21 },
    { name: 'R. Jiménez', position: 'Attacker', number: 9 },
    { name: 'G. Martínez', position: 'Attacker', number: 22 },
    { name: 'J. Quiñones', position: 'Midfielder', number: 16 },
    { name: 'A. Vega', position: 'Attacker', number: 10 },
  ],
  'South Africa': [
    { name: 'S. Chaine', position: 'Goalkeeper', number: 16 },
    { name: 'R. Goss', position: 'Goalkeeper', number: 22 },
    { name: 'R. Williams', position: 'Goalkeeper', number: 1 },
    { name: 'B. Cross', position: 'Defender', number: 26 },
    { name: 'S. Kabini', position: 'Defender', number: 18 },
    { name: 'O. Makhanya', position: 'Defender', number: 24 },
    { name: 'M. Mbokazi', position: 'Defender', number: 14 },
    { name: 'A. Modiba', position: 'Defender', number: 6 },
    { name: 'K. Mudau', position: 'Defender', number: 20 },
    { name: 'K. Ndamane', position: 'Defender', number: 3 },
    { name: 'I. Okon', position: 'Defender', number: 21 },
    { name: 'N. Sibisi', position: 'Defender', number: 19 },
    { name: 'T. Matuludi', position: 'Defender', number: 2 },
    { name: 'J. Adams', position: 'Midfielder', number: 23 },
    { name: 'T. Mbatha', position: 'Midfielder', number: 5 },
    { name: 'T. Mokoena', position: 'Midfielder', number: 4 },
    { name: 'S. Sithole', position: 'Midfielder', number: 13 },
    { name: 'T. Zwane', position: 'Midfielder', number: 11 },
    { name: 'O. Appollis', position: 'Attacker', number: 7 },
    { name: 'L. Foster', position: 'Attacker', number: 9 },
    { name: 'E. Makgopa', position: 'Attacker', number: 99 },
    { name: 'T. Maseko', position: 'Attacker', number: 12 },
    { name: 'R. Mofokeng', position: 'Attacker', number: 10 },
    { name: 'T. Moremi', position: 'Midfielder', number: 8 },
    { name: 'I. Rayners', position: 'Attacker', number: 15 },
    { name: 'K. Sebelebele', position: 'Midfielder', number: 25 },
  ],
  'South Korea': [
    { name: 'Jo Hyeon-Woo', position: 'Goalkeeper', number: 21 },
    { name: 'Kim Seung-Gyu', position: 'Goalkeeper', number: 12 },
    { name: 'Song Bum-Keun', position: 'Goalkeeper', number: 1 },
    { name: 'Cho Wi-Je', position: 'Defender', number: 5 },
    { name: 'Kim Min-Jae', position: 'Defender', number: 2 },
    { name: 'Kim Moon-Hwan', position: 'Defender', number: 15 },
    { name: 'Kim Tae-Hyeon', position: 'Defender', number: 9 },
    { name: 'Lee Han-Beom', position: 'Defender', number: 18 },
    { name: 'Park Jin-Seop', position: 'Midfielder', number: 22 },
    { name: 'Lee Tae-Seok', position: 'Midfielder', number: 7 },
    { name: 'Seol Young-Woo', position: 'Midfielder', number: 16 },
    { name: 'J. Castrop', position: 'Midfielder', number: 19 },
    { name: 'Lee Gi-Hyuk', position: 'Defender', number: 10 },
    { name: 'Bae Jun-Ho', position: 'Attacker', number: 25 },
    { name: 'Eom Ji-Sung', position: 'Attacker', number: 23 },
    { name: 'Hwang In-Beom', position: 'Midfielder', number: 24 },
    { name: 'Kim Jin-Gyu', position: 'Midfielder', number: 25 },
    { name: 'Lee Dong-Gyeong', position: 'Attacker', number: 11 },
    { name: 'Lee Jae-Sung', position: 'Midfielder', number: 8 },
    { name: 'Lee Kang-In', position: 'Midfielder', number: 17 },
    { name: 'Paik Seung-Ho', position: 'Midfielder', number: 4 },
    { name: 'Yang Hyun-Jun', position: 'Attacker', number: 26 },
    { name: 'Hwang Hee-Chan', position: 'Attacker', number: 20 },
    { name: 'Cho Gue-Sung', position: 'Attacker', number: 14 },
    { name: 'Oh Hyeon-Gyu', position: 'Attacker', number: 3 },
    { name: 'Son Heung-Min', position: 'Attacker', number: 13 },
  ],
  'Czechia': [
    { name: 'L. Hornícek', position: 'Goalkeeper', number: 23 },
    { name: 'M. Kovár', position: 'Goalkeeper', number: 1 },
    { name: 'J. Stanek', position: 'Goalkeeper', number: 16 },
    { name: 'S. Chaloupek', position: 'Defender', number: 6 },
    { name: 'V. Coufal', position: 'Defender', number: 5 },
    { name: 'T. Holes', position: 'Defender', number: 3 },
    { name: 'R. Hranác', position: 'Defender', number: 4 },
    { name: 'D. Jurásek', position: 'Defender', number: 14 },
    { name: 'L. Krejcí', position: 'Defender', number: 7 },
    { name: 'J. Zelený', position: 'Defender', number: 20 },
    { name: 'D. Zima', position: 'Defender', number: 2 },
    { name: 'D. Doudera', position: 'Midfielder', number: 21 },
    { name: 'L. Cerv', position: 'Midfielder', number: 12 },
    { name: 'V. Darida', position: 'Midfielder', number: 8 },
    { name: 'L. Provod', position: 'Attacker', number: 17 },
    { name: 'M. Sadílek', position: 'Midfielder', number: 18 },
    { name: 'H. Sochurek', position: 'Midfielder', number: 25 },
    { name: 'A. Sojka', position: 'Midfielder', number: 24 },
    { name: 'T. Soucek', position: 'Midfielder', number: 22 },
    { name: 'P. Sulc', position: 'Attacker', number: 15 },
    { name: 'T. Chorý', position: 'Attacker', number: 19 },
    { name: 'M. Chytil', position: 'Attacker', number: 13 },
    { name: 'A. Hlozek', position: 'Attacker', number: 9 },
    { name: 'J. Kuchta', position: 'Attacker', number: 11 },
    { name: 'P. Schick', position: 'Attacker', number: 10 },
    { name: 'D. Visinský', position: 'Midfielder', number: 26 },
  ],
  'Canada': [
    { name: 'M. Crépeau', position: 'Goalkeeper', number: 16 },
    { name: 'O. Goodman', position: 'Goalkeeper', number: 18 },
    { name: 'D. St. Clair', position: 'Goalkeeper', number: 1 },
    { name: 'D. Cornelius', position: 'Defender', number: 13 },
    { name: 'L. De Fougerolles', position: 'Defender', number: 4 },
    { name: 'R. Laryea', position: 'Defender', number: 22 },
    { name: 'J. Waterman', position: 'Defender', number: 5 },
    { name: 'A. Johnston', position: 'Defender', number: 2 },
    { name: 'A. Jones', position: 'Defender', number: 3 },
    { name: 'M. Bombito', position: 'Defender', number: 15 },
    { name: 'A. Davies', position: 'Defender', number: 19 },
    { name: 'N. Sigur', position: 'Midfielder', number: 23 },
    { name: 'J. Shaffelburg', position: 'Midfielder', number: 14 },
    { name: 'L. Millar', position: 'Midfielder', number: 11 },
    { name: 'M. Choinière', position: 'Midfielder', number: 6 },
    { name: 'S. Eustáquio', position: 'Midfielder', number: 7 },
    { name: 'I. Koné', position: 'Midfielder', number: 8 },
    { name: 'J. Osorio', position: 'Midfielder', number: 21 },
    { name: 'N. Saliba', position: 'Midfielder', number: 25 },
    { name: 'M. Flores', position: 'Midfielder', number: 26 },
    { name: 'T. Buchanan', position: 'Midfielder', number: 17 },
    { name: 'J. David', position: 'Attacker', number: 10 },
    { name: 'P. David', position: 'Attacker', number: 24 },
    { name: 'C. Larin', position: 'Attacker', number: 9 },
    { name: 'A. Ahmed', position: 'Midfielder', number: 20 },
    { name: 'T. Oluwaseyi', position: 'Attacker', number: 12 },
  ],
  'Bosnia and Herzegovina': [
    { name: 'M. Jurkas', position: 'Goalkeeper', number: 12 },
    { name: 'N. Vasilj', position: 'Goalkeeper', number: 1 },
    { name: 'M. Zlomislic', position: 'Goalkeeper', number: 22 },
    { name: 'N. Celik', position: 'Defender', number: 24 },
    { name: 'A. Dedic', position: 'Defender', number: 7 },
    { name: 'D. Hadzikadunic', position: 'Defender', number: 3 },
    { name: 'N. Katic', position: 'Defender', number: 18 },
    { name: 'S. Kolasinac', position: 'Defender', number: 5 },
    { name: 'T. Muharemovic', position: 'Defender', number: 4 },
    { name: 'N. Mujakic', position: 'Defender', number: 2 },
    { name: 'S. Radeljic', position: 'Defender', number: 21 },
    { name: 'I. Basic', position: 'Midfielder', number: 13 },
    { name: 'A. Gigovic', position: 'Midfielder', number: 8 },
    { name: 'A. Hadziahmetovic', position: 'Midfielder', number: 16 },
    { name: 'Ermin Mahmic', position: 'Midfielder', number: 26 },
    { name: 'I. Sunjic', position: 'Midfielder', number: 14 },
    { name: 'B. Tahirovic', position: 'Midfielder', number: 6 },
    { name: 'A. Memic', position: 'Midfielder', number: 15 },
    { name: 'D. Burnic', position: 'Midfielder', number: 17 },
    { name: 'Kerim-Sam Alajbegovic', position: 'Midfielder', number: 19 },
    { name: 'E. Bajraktarevic', position: 'Attacker', number: 20 },
    { name: 'S. Bazdar', position: 'Attacker', number: 9 },
    { name: 'E. Demirovic', position: 'Attacker', number: 10 },
    { name: 'E. Dzeko', position: 'Attacker', number: 11 },
    { name: 'J. Lukic', position: 'Attacker', number: 25 },
    { name: 'H. Tabakovic', position: 'Attacker', number: 23 },
  ],
  'Qatar': [
    { name: 'Mahmud Abunada', position: 'Goalkeeper', number: 1 },
    { name: 'Meshaal Barsham', position: 'Goalkeeper', number: 22 },
    { name: 'Salah Zakaria', position: 'Goalkeeper', number: 21 },
    { name: 'Homam Ahmed', position: 'Defender', number: 14 },
    { name: 'Sultan Al Braik', position: 'Defender', number: 18 },
    { name: 'A. Al Hussain', position: 'Defender', number: 25 },
    { name: 'A. Al Oui', position: 'Defender', number: 13 },
    { name: 'Jassem Gaber', position: 'Midfielder', number: 5 },
    { name: 'Boualem Khoukhi', position: 'Defender', number: 16 },
    { name: 'Lucas Mendes', position: 'Defender', number: 3 },
    { name: 'G. Laye', position: 'Midfielder', number: 4 },
    { name: 'Pedro Miguel', position: 'Defender', number: 2 },
    { name: 'Assim Madibo', position: 'Midfielder', number: 23 },
    { name: 'Ahmed Al Ganehi', position: 'Attacker', number: 17 },
    { name: 'Abdulaziz Hatem', position: 'Midfielder', number: 6 },
    { name: 'Karim Boudiaf', position: 'Midfielder', number: 12 },
    { name: 'Ahmed Fathi', position: 'Midfielder', number: 20 },
    { name: 'Hassan Al Haydos', position: 'Attacker', number: 10 },
    { name: 'Mohamed Al Manai', position: 'Midfielder', number: 26 },
    { name: 'Y. Abdurisag', position: 'Attacker', number: 15 },
    { name: 'Akram Afif', position: 'Attacker', number: 11 },
    { name: 'Ahmed Alaa', position: 'Attacker', number: 7 },
    { name: 'Almoez Ali', position: 'Attacker', number: 19 },
    { name: 'Edmilson Junior', position: 'Attacker', number: 8 },
    { name: 'Tahsin Jamshid', position: 'Attacker', number: 24 },
    { name: 'Mohammed Muntari', position: 'Attacker', number: 9 },
  ],
  'Switzerland': [
    { name: 'M. Keller', position: 'Goalkeeper', number: 21 },
    { name: 'G. Kobel', position: 'Goalkeeper', number: 1 },
    { name: 'Y. Mvogo', position: 'Goalkeeper', number: 12 },
    { name: 'M. Akanji', position: 'Defender', number: 5 },
    { name: 'A. Amenda', position: 'Defender', number: 24 },
    { name: 'E. Cömert', position: 'Defender', number: 18 },
    { name: 'N. Elvedi', position: 'Defender', number: 4 },
    { name: 'L. Jaquez', position: 'Defender', number: 25 },
    { name: 'M. Muheim', position: 'Defender', number: 2 },
    { name: 'R. Rodríguez', position: 'Defender', number: 13 },
    { name: 'S. Widmer', position: 'Defender', number: 3 },
    { name: 'M. Aebischer', position: 'Midfielder', number: 20 },
    { name: 'R. Freuler', position: 'Midfielder', number: 8 },
    { name: 'A. Jashari', position: 'Midfielder', number: 14 },
    { name: 'D. Sow', position: 'Midfielder', number: 15 },
    { name: 'G. Xhaka', position: 'Midfielder', number: 10 },
    { name: 'D. Zakaria', position: 'Midfielder', number: 6 },
    { name: 'C. Fassnacht', position: 'Midfielder', number: 16 },
    { name: 'C. Itten', position: 'Attacker', number: 26 },
    { name: 'F. Rieder', position: 'Midfielder', number: 22 },
    { name: 'R. Vargas', position: 'Attacker', number: 17 },
    { name: 'Z. Amdouni', position: 'Attacker', number: 23 },
    { name: 'B. Embolo', position: 'Attacker', number: 7 },
    { name: 'J. Manzambi', position: 'Attacker', number: 9 },
    { name: 'N. Okafor', position: 'Attacker', number: 19 },
    { name: 'D. Ndoye', position: 'Midfielder', number: 11 },
  ],
  'Brazil': [
    { name: 'Alisson Becker', position: 'Goalkeeper', number: 1 },
    { name: 'Ederson', position: 'Goalkeeper', number: 23 },
    { name: 'Weverton', position: 'Goalkeeper', number: 12 },
    { name: 'Alex Sandro', position: 'Defender', number: 6 },
    { name: 'Bremer', position: 'Defender', number: 14 },
    { name: 'Gabriel Magalhães', position: 'Defender', number: 3 },
    { name: 'Ibañez', position: 'Defender', number: 24 },
    { name: 'Léo Pereira', position: 'Defender', number: 15 },
    { name: 'Marquinhos', position: 'Defender', number: 4 },
    { name: 'Douglas Santos', position: 'Defender', number: 16 },
    { name: 'Wesley', position: 'Defender', number: 2 },
    { name: 'Danilo', position: 'Defender', number: 13 },
    { name: 'Bruno Guimarães', position: 'Midfielder', number: 8 },
    { name: 'Casemiro', position: 'Midfielder', number: 5 },
    { name: 'Fabinho', position: 'Midfielder', number: 17 },
    { name: 'Lucas Paquetá', position: 'Midfielder', number: 20 },
    { name: 'Danilo Santos', position: 'Midfielder', number: 18 },
    { name: 'Matheus Cunha', position: 'Attacker', number: 9 },
    { name: 'Endrick', position: 'Attacker', number: 19 },
    { name: 'Luiz Henrique', position: 'Attacker', number: 21 },
    { name: 'Gabriel Martinelli', position: 'Attacker', number: 22 },
    { name: 'Neymar', position: 'Attacker', number: 10 },
    { name: 'Raphinha', position: 'Midfielder', number: 11 },
    { name: 'Rayan', position: 'Attacker', number: 26 },
    { name: 'Thiago', position: 'Attacker', number: 25 },
    { name: 'Vinícius Júnior', position: 'Attacker', number: 7 },
  ],
  'Morocco': [
    { name: 'Y. Bounou', position: 'Goalkeeper', number: 1 },
    { name: 'M. Mohamedi', position: 'Goalkeeper', number: 12 },
    { name: 'A. Tagnaouti', position: 'Goalkeeper', number: 22 },
    { name: 'N. Aguerd', position: 'Defender', number: 5 },
    { name: 'I. Diop', position: 'Defender', number: 14 },
    { name: 'Z. El Ouahdi', position: 'Defender', number: 13 },
    { name: 'A. Hakimi', position: 'Defender', number: 2 },
    { name: 'R. Halhal', position: 'Defender', number: 25 },
    { name: 'N. Mazraoui', position: 'Defender', number: 3 },
    { name: 'C. Riad', position: 'Defender', number: 18 },
    { name: 'A. Salah-Eddine', position: 'Defender', number: 26 },
    { name: 'Y. Belammari', position: 'Defender', number: 19 },
    { name: 'S. Amrabat', position: 'Midfielder', number: 4 },
    { name: 'A. Bouaddi', position: 'Midfielder', number: 6 },
    { name: 'N. El Aynaoui', position: 'Midfielder', number: 24 },
    { name: 'B. El Khannouss', position: 'Midfielder', number: 23 },
    { name: 'S. El Mourabet', position: 'Midfielder', number: 15 },
    { name: 'A. Ounahi', position: 'Midfielder', number: 8 },
    { name: 'I. Saibari', position: 'Attacker', number: 11 },
    { name: 'C. Talbi', position: 'Midfielder', number: 7 },
    { name: 'Gessime Yassine', position: 'Attacker', number: 16 },
    { name: 'Brahim Díaz', position: 'Midfielder', number: 10 },
    { name: 'A. Amaimouni', position: 'Midfielder', number: 21 },
    { name: 'A. El Kaabi', position: 'Attacker', number: 20 },
    { name: 'A. Ezzalzouli', position: 'Midfielder', number: 17 },
    { name: 'S. Rahimi', position: 'Attacker', number: 9 },
  ],
  'Haiti': [
    { name: 'J. Duverger', position: 'Goalkeeper', number: 23 },
    { name: 'A. Pierre', position: 'Goalkeeper', number: 12 },
    { name: 'J. Placide', position: 'Goalkeeper', number: 1 },
    { name: 'C. Arcus', position: 'Defender', number: 2 },
    { name: 'K. Thermoncy', position: 'Defender', number: 3 },
    { name: 'Ricardo Ade', position: 'Defender', number: 4 },
    { name: 'H. Delcroix', position: 'Defender', number: 5 },
    { name: 'J. Duverne', position: 'Defender', number: 22 },
    { name: 'M. Expérience', position: 'Defender', number: 8 },
    { name: 'D. Lacroix', position: 'Defender', number: 13 },
    { name: 'W. Paugain', position: 'Defender', number: 24 },
    { name: 'J. Bellegarde', position: 'Midfielder', number: 10 },
    { name: 'D. Jean-Jacques', position: 'Midfielder', number: 17 },
    { name: 'L. Pierre', position: 'Midfielder', number: 14 },
    { name: 'W. Pierre', position: 'Midfielder', number: 26 },
    { name: 'C. F. Sainte', position: 'Midfielder', number: 6 },
    { name: 'D. Simon', position: 'Midfielder', number: 25 },
    { name: 'J. Casimir', position: 'Attacker', number: 21 },
    { name: 'L. Deedson', position: 'Midfielder', number: 11 },
    { name: 'D. Etienne', position: 'Attacker', number: 7 },
    { name: 'Y. Fortuné', position: 'Attacker', number: 19 },
    { name: 'W. Isidor', position: 'Attacker', number: 18 },
    { name: 'L. Joseph', position: 'Attacker', number: 16 },
    { name: 'D. Nazon', position: 'Attacker', number: 9 },
    { name: 'F. Pierrot', position: 'Attacker', number: 20 },
    { name: 'R. Providence', position: 'Midfielder', number: 15 },
  ],
  'Scotland': [
    { name: 'C. Gordon', position: 'Goalkeeper', number: 21 },
    { name: 'A. Gunn', position: 'Goalkeeper', number: 1 },
    { name: 'L. Kelly', position: 'Goalkeeper', number: 12 },
    { name: 'G. Hanley', position: 'Defender', number: 5 },
    { name: 'J. Hendry', position: 'Defender', number: 13 },
    { name: 'A. Hickey', position: 'Defender', number: 2 },
    { name: 'D. Hyam', position: 'Defender', number: 16 },
    { name: 'S. McKenna', position: 'Defender', number: 26 },
    { name: 'N. Patterson', position: 'Defender', number: 22 },
    { name: 'A. Ralston', position: 'Defender', number: 24 },
    { name: 'A. Robertson', position: 'Defender', number: 3 },
    { name: 'J. Souttar', position: 'Defender', number: 15 },
    { name: 'K. Tierney', position: 'Defender', number: 6 },
    { name: 'R. Christie', position: 'Midfielder', number: 11 },
    { name: 'L. Ferguson', position: 'Midfielder', number: 19 },
    { name: 'T. Fletcher', position: 'Midfielder', number: 8 },
    { name: 'J. McGinn', position: 'Midfielder', number: 7 },
    { name: 'K. McLean', position: 'Midfielder', number: 23 },
    { name: 'S. McTominay', position: 'Midfielder', number: 4 },
    { name: 'C. Adams', position: 'Attacker', number: 10 },
    { name: 'L. Dykes', position: 'Attacker', number: 9 },
    { name: 'B. Doak', position: 'Midfielder', number: 17 },
    { name: 'G. Hirst', position: 'Attacker', number: 18 },
    { name: 'L. Shankland', position: 'Attacker', number: 20 },
    { name: 'R. Stewart', position: 'Attacker', number: 14 },
    { name: 'Findlay Curtis', position: 'Attacker', number: 25 },
  ],
  'USA': [
    { name: 'C. Brady', position: 'Goalkeeper', number: 25 },
    { name: 'M. Freese', position: 'Goalkeeper', number: 24 },
    { name: 'M. Turner', position: 'Goalkeeper', number: 1 },
    { name: 'S. Dest', position: 'Midfielder', number: 2 },
    { name: 'A. Freeman', position: 'Defender', number: 16 },
    { name: 'M. McKenzie', position: 'Defender', number: 22 },
    { name: 'T. Ream', position: 'Defender', number: 13 },
    { name: 'C. Richards', position: 'Defender', number: 3 },
    { name: 'A. Robinson', position: 'Defender', number: 5 },
    { name: 'M. Robinson', position: 'Defender', number: 12 },
    { name: 'J. Scally', position: 'Defender', number: 23 },
    { name: 'A. Trusty', position: 'Defender', number: 6 },
    { name: 'M. Arfsten', position: 'Midfielder', number: 18 },
    { name: 'S. Berhalter', position: 'Midfielder', number: 14 },
    { name: 'W. McKennie', position: 'Midfielder', number: 8 },
    { name: 'G. Reyna', position: 'Midfielder', number: 7 },
    { name: 'C. Roldan', position: 'Midfielder', number: 15 },
    { name: 'M. Tillman', position: 'Midfielder', number: 17 },
    { name: 'T. Adams', position: 'Midfielder', number: 4 },
    { name: 'T. Weah', position: 'Attacker', number: 21 },
    { name: 'A. Zendejas', position: 'Attacker', number: 26 },
    { name: 'B. Aaronson', position: 'Midfielder', number: 11 },
    { name: 'F. Balogun', position: 'Attacker', number: 20 },
    { name: 'R. Pepi', position: 'Attacker', number: 9 },
    { name: 'C. Pulisic', position: 'Midfielder', number: 10 },
    { name: 'H. Wright', position: 'Attacker', number: 19 },
  ],
  'Paraguay': [
    { name: 'R. Fernandez', position: 'Goalkeeper', number: 1 },
    { name: 'O. Gill', position: 'Goalkeeper', number: 12 },
    { name: 'G. Olveira', position: 'Goalkeeper', number: 22 },
    { name: 'O. Alderete', position: 'Defender', number: 3 },
    { name: 'J. Alonso', position: 'Defender', number: 6 },
    { name: 'J. Cáceres', position: 'Defender', number: 4 },
    { name: 'F. Balbuena', position: 'Defender', number: 5 },
    { name: 'G. Gómez', position: 'Defender', number: 15 },
    { name: 'A. Maidana', position: 'Defender', number: 26 },
    { name: 'G. Velázquez', position: 'Defender', number: 2 },
    { name: 'J. Canale', position: 'Defender', number: 13 },
    { name: 'D. Bobadilla', position: 'Midfielder', number: 16 },
    { name: 'G. Caballero', position: 'Midfielder', number: 24 },
    { name: 'A. Cubas', position: 'Midfielder', number: 14 },
    { name: 'M. Galarza', position: 'Midfielder', number: 23 },
    { name: 'D. Gómez', position: 'Midfielder', number: 8 },
    { name: 'Maurício', position: 'Midfielder', number: 11 },
    { name: 'B. Ojeda', position: 'Midfielder', number: 20 },
    { name: 'R. Sosa', position: 'Midfielder', number: 7 },
    { name: 'M. Almirón', position: 'Midfielder', number: 10 },
    { name: 'A. Romero', position: 'Attacker', number: 17 },
    { name: 'A. Arce', position: 'Attacker', number: 18 },
    { name: 'G. Ávalos', position: 'Attacker', number: 21 },
    { name: 'J. Enciso', position: 'Attacker', number: 19 },
    { name: 'I. Pitta', position: 'Attacker', number: 25 },
    { name: 'A. Sanabria', position: 'Attacker', number: 9 },
  ],
  'Australia': [
    { name: 'P. Beach', position: 'Goalkeeper', number: 18 },
    { name: 'P. Izzo', position: 'Goalkeeper', number: 12 },
    { name: 'M. Ryan', position: 'Goalkeeper', number: 1 },
    { name: 'A. Behich', position: 'Midfielder', number: 16 },
    { name: 'J. Bos', position: 'Defender', number: 5 },
    { name: 'C. Burgess', position: 'Defender', number: 21 },
    { name: 'A. Circati', position: 'Defender', number: 3 },
    { name: 'J. Geria', position: 'Defender', number: 6 },
    { name: 'L. Herrington', position: 'Defender', number: 25 },
    { name: 'H. Souttar', position: 'Defender', number: 19 },
    { name: 'M. Degenek', position: 'Defender', number: 2 },
    { name: 'J. Italiano', position: 'Defender', number: 4 },
    { name: 'K. Trewin', position: 'Midfielder', number: 15 },
    { name: 'J. Irvine', position: 'Midfielder', number: 22 },
    { name: 'C. Devlin', position: 'Midfielder', number: 14 },
    { name: 'A. O Neill', position: 'Midfielder', number: 13 },
    { name: 'Paul Okon-Engstler', position: 'Midfielder', number: 24 },
    { name: 'C. Metcalfe', position: 'Midfielder', number: 8 },
    { name: 'A. Hrustic', position: 'Midfielder', number: 10 },
    { name: 'C. Volpato', position: 'Attacker', number: 20 },
    { name: 'N. Irankunda', position: 'Attacker', number: 17 },
    { name: 'M. Leckie', position: 'Attacker', number: 7 },
    { name: 'A. Mabil', position: 'Midfielder', number: 11 },
    { name: 'T. Yengi', position: 'Attacker', number: 26 },
    { name: 'M. Touré', position: 'Attacker', number: 9 },
    { name: 'N. Velupillay', position: 'Attacker', number: 23 },
  ],
  'Türkiye': [
    { name: 'A. Bayindir', position: 'Goalkeeper', number: 12 },
    { name: 'U. Çakir', position: 'Goalkeeper', number: 23 },
    { name: 'M. Günok', position: 'Goalkeeper', number: 1 },
    { name: 'S. Akaydin', position: 'Defender', number: 25 },
    { name: 'A. Bardakci', position: 'Defender', number: 14 },
    { name: 'Z. Çelik', position: 'Defender', number: 2 },
    { name: 'M. Demiral', position: 'Defender', number: 3 },
    { name: 'E. Elmali', position: 'Defender', number: 13 },
    { name: 'O. Kabak', position: 'Defender', number: 15 },
    { name: 'F. Kadioglu', position: 'Defender', number: 20 },
    { name: 'M. Müldür', position: 'Defender', number: 18 },
    { name: 'Ç. Söyüncü', position: 'Defender', number: 4 },
    { name: 'H. Çalhanoglu', position: 'Midfielder', number: 10 },
    { name: 'K. Ayhan', position: 'Defender', number: 22 },
    { name: 'O. Kokçu', position: 'Midfielder', number: 6 },
    { name: 'S. Özcan', position: 'Midfielder', number: 5 },
    { name: 'I. Yüksek', position: 'Midfielder', number: 16 },
    { name: 'C. Uzun', position: 'Midfielder', number: 26 },
    { name: 'O. Aydin', position: 'Attacker', number: 24 },
    { name: 'A. Güler', position: 'Midfielder', number: 8 },
    { name: 'Y. Akgün', position: 'Attacker', number: 19 },
    { name: 'K. Aktürkoglu', position: 'Attacker', number: 7 },
    { name: 'D. Gül', position: 'Attacker', number: 9 },
    { name: 'I. Kahveci', position: 'Midfielder', number: 17 },
    { name: 'K. Yildiz', position: 'Attacker', number: 11 },
    { name: 'B. Yilmaz', position: 'Midfielder', number: 21 },
  ],
  'Germany': [
    { name: 'O. Baumann', position: 'Goalkeeper', number: 12 },
    { name: 'M. Neuer', position: 'Goalkeeper', number: 1 },
    { name: 'A. Nübel', position: 'Goalkeeper', number: 21 },
    { name: 'W. Anton', position: 'Defender', number: 3 },
    { name: 'N. Brown', position: 'Defender', number: 18 },
    { name: 'D. Raum', position: 'Defender', number: 22 },
    { name: 'A. Rüdiger', position: 'Defender', number: 2 },
    { name: 'N. Schlotterbeck', position: 'Defender', number: 15 },
    { name: 'J. Tah', position: 'Defender', number: 4 },
    { name: 'M. Thiaw', position: 'Defender', number: 24 },
    { name: 'J. Kimmich', position: 'Defender', number: 6 },
    { name: 'N. Amiri', position: 'Midfielder', number: 20 },
    { name: 'L. Goretzka', position: 'Midfielder', number: 8 },
    { name: 'P. Groß', position: 'Midfielder', number: 13 },
    { name: 'L. Karl', position: 'Midfielder', number: 25 },
    { name: 'J. Leweling', position: 'Attacker', number: 9 },
    { name: 'J. Musiala', position: 'Midfielder', number: 10 },
    { name: 'F. Nmecha', position: 'Midfielder', number: 23 },
    { name: 'A. Pavlovic', position: 'Midfielder', number: 5 },
    { name: 'L. Sané', position: 'Midfielder', number: 19 },
    { name: 'A. Stiller', position: 'Midfielder', number: 16 },
    { name: 'F. Wirtz', position: 'Midfielder', number: 17 },
    { name: 'K. Havertz', position: 'Attacker', number: 7 },
    { name: 'M. Beier', position: 'Attacker', number: 14 },
    { name: 'D. Undav', position: 'Attacker', number: 26 },
    { name: 'N. Woltemade', position: 'Attacker', number: 11 },
  ],
  'Curaçao': [
    { name: 'T. Bodak', position: 'Goalkeeper', number: 25 },
    { name: 'T. Doornbusch', position: 'Goalkeeper', number: 26 },
    { name: 'E. Room', position: 'Goalkeeper', number: 1 },
    { name: 'R. Bazoer', position: 'Defender', number: 23 },
    { name: 'J. Brenet', position: 'Defender', number: 20 },
    { name: 'S. Floranus', position: 'Defender', number: 5 },
    { name: 'Deveron Fonville', position: 'Defender', number: 24 },
    { name: 'J. Gaari', position: 'Defender', number: 3 },
    { name: 'S. Sambo', position: 'Defender', number: 2 },
    { name: 'R. van Eijma', position: 'Defender', number: 4 },
    { name: 'A. Obispo', position: 'Defender', number: 18 },
    { name: 'L. Bacuna', position: 'Midfielder', number: 10 },
    { name: 'A. Martha', position: 'Midfielder', number: 15 },
    { name: 'T. Noslin', position: 'Midfielder', number: 13 },
    { name: 'L. Comenencia', position: 'Midfielder', number: 8 },
    { name: 'K. Felida', position: 'Midfielder', number: 22 },
    { name: 'T. Chong', position: 'Midfielder', number: 21 },
    { name: 'G. Roemeratoe', position: 'Midfielder', number: 6 },
    { name: 'J. Bacuna', position: 'Midfielder', number: 7 },
    { name: 'J. Antonisse', position: 'Attacker', number: 11 },
    { name: 'B. Kuwas', position: 'Attacker', number: 17 },
    { name: 'K. Gorré', position: 'Attacker', number: 14 },
    { name: 'S. Hansen', position: 'Attacker', number: 12 },
    { name: 'G. Kastaneer', position: 'Attacker', number: 19 },
    { name: 'J. Locadia', position: 'Attacker', number: 9 },
    { name: 'J. Margaritha', position: 'Attacker', number: 16 },
  ],
  'Ivory Coast': [
    { name: 'Y. Fofana', position: 'Goalkeeper', number: 1 },
    { name: 'M. Koné', position: 'Goalkeeper', number: 16 },
    { name: 'A. Lafont', position: 'Goalkeeper', number: 23 },
    { name: 'E. Agbadou', position: 'Defender', number: 20 },
    { name: 'O. Diomande', position: 'Defender', number: 2 },
    { name: 'G. Doué', position: 'Defender', number: 17 },
    { name: 'G. Konan', position: 'Defender', number: 3 },
    { name: 'O. Kossounou', position: 'Defender', number: 7 },
    { name: 'E. Ndicka', position: 'Defender', number: 21 },
    { name: 'C. Operi', position: 'Defender', number: 13 },
    { name: 'W. Singo', position: 'Defender', number: 5 },
    { name: 'S. Fofana', position: 'Midfielder', number: 6 },
    { name: 'C. Inao Oulai', position: 'Midfielder', number: 26 },
    { name: 'F. Kessié', position: 'Midfielder', number: 8 },
    { name: 'I. Sangaré', position: 'Midfielder', number: 18 },
    { name: 'J. Seri', position: 'Midfielder', number: 4 },
    { name: 'P. Guiagon', position: 'Midfielder', number: 25 },
    { name: 'B. Touré', position: 'Attacker', number: 24 },
    { name: 'S. Adingra', position: 'Attacker', number: 10 },
    { name: 'A. Bonny', position: 'Attacker', number: 9 },
    { name: 'O. Diakité', position: 'Midfielder', number: 14 },
    { name: 'A. Diallo', position: 'Attacker', number: 15 },
    { name: 'Y. Diomande', position: 'Midfielder', number: 11 },
    { name: 'E. Guessand', position: 'Attacker', number: 22 },
    { name: 'N. Pépé', position: 'Attacker', number: 19 },
    { name: 'E. Wahi', position: 'Attacker', number: 12 },
  ],
  'Ecuador': [
    { name: 'H. Galíndez', position: 'Goalkeeper', number: 1 },
    { name: 'M. Ramírez', position: 'Goalkeeper', number: 12 },
    { name: 'G. Valle', position: 'Goalkeeper', number: 22 },
    { name: 'P. Estupiñán', position: 'Defender', number: 7 },
    { name: 'P. Hincapié', position: 'Defender', number: 3 },
    { name: 'Y. Medina', position: 'Midfielder', number: 26 },
    { name: 'J. Ordoñez', position: 'Defender', number: 4 },
    { name: 'W. Pacho', position: 'Defender', number: 6 },
    { name: 'J. Porozo', position: 'Defender', number: 25 },
    { name: 'A. Preciado', position: 'Defender', number: 17 },
    { name: 'F. Torres', position: 'Defender', number: 2 },
    { name: 'J. Alcívar', position: 'Midfielder', number: 5 },
    { name: 'M. Caicedo', position: 'Midfielder', number: 23 },
    { name: 'D. Castillo', position: 'Midfielder', number: 6 },
    { name: 'A. Franco', position: 'Defender', number: 21 },
    { name: 'K. Páez', position: 'Attacker', number: 10 },
    { name: 'A. Minda', position: 'Midfielder', number: 14 },
    { name: 'A. Valencia', position: 'Midfielder', number: 8 },
    { name: 'P. Vite', position: 'Midfielder', number: 15 },
    { name: 'K. Rodríguez', position: 'Attacker', number: 11 },
    { name: 'J. Yeboah', position: 'Attacker', number: 9 },
    { name: 'N. Angulo', position: 'Attacker', number: 20 },
    { name: 'J. Caicedo', position: 'Attacker', number: 16 },
    { name: 'Jeremy Arévalo', position: 'Attacker', number: 24 },
    { name: 'G. Plata', position: 'Attacker', number: 19 },
    { name: 'E. Valencia', position: 'Attacker', number: 13 },
  ],
  'Netherlands': [
    { name: 'M. Flekken', position: 'Goalkeeper', number: 23 },
    { name: 'R. Roefs', position: 'Goalkeeper', number: 13 },
    { name: 'B. Verbruggen', position: 'Goalkeeper', number: 1 },
    { name: 'N. Aké', position: 'Defender', number: 5 },
    { name: 'D. Dumfries', position: 'Defender', number: 22 },
    { name: 'J. Hato', position: 'Defender', number: 25 },
    { name: 'J. Timber', position: 'Defender', number: 2 },
    { name: 'V. van Dijk', position: 'Defender', number: 4 },
    { name: 'J. van Hecke', position: 'Defender', number: 6 },
    { name: 'M. van de Ven', position: 'Defender', number: 15 },
    { name: 'M. Wieffer', position: 'Defender', number: 12 },
    { name: 'R. Gravenberch', position: 'Midfielder', number: 8 },
    { name: 'T. Koopmeiners', position: 'Midfielder', number: 20 },
    { name: 'T. Reijnders', position: 'Midfielder', number: 14 },
    { name: 'G. Til', position: 'Midfielder', number: 16 },
    { name: 'Q. Timber', position: 'Midfielder', number: 26 },
    { name: 'F. de Jong', position: 'Midfielder', number: 21 },
    { name: 'M. de Roon', position: 'Midfielder', number: 3 },
    { name: 'J. Kluivert', position: 'Attacker', number: 7 },
    { name: 'B. Brobbey', position: 'Attacker', number: 19 },
    { name: 'M. Depay', position: 'Attacker', number: 10 },
    { name: 'C. Gakpo', position: 'Attacker', number: 11 },
    { name: 'N. Lang', position: 'Attacker', number: 17 },
    { name: 'D. Malen', position: 'Attacker', number: 18 },
    { name: 'C. Summerville', position: 'Attacker', number: 24 },
    { name: 'W. Weghorst', position: 'Attacker', number: 9 },
  ],
  'Japan': [
    { name: 'T. Hayakawa', position: 'Goalkeeper', number: 23 },
    { name: 'K. Osako', position: 'Goalkeeper', number: 12 },
    { name: 'Z. Suzuki', position: 'Goalkeeper', number: 1 },
    { name: 'K. Itakura', position: 'Defender', number: 4 },
    { name: 'H. Ito', position: 'Defender', number: 21 },
    { name: 'Y. Nagatomo', position: 'Defender', number: 5 },
    { name: 'A. Seko', position: 'Defender', number: 20 },
    { name: 'Y. Sugawara', position: 'Defender', number: 2 },
    { name: 'J. Suzuki', position: 'Defender', number: 25 },
    { name: 'S. Taniguchi', position: 'Defender', number: 3 },
    { name: 'T. Tomiyasu', position: 'Defender', number: 15 },
    { name: 'T. Watanabe', position: 'Defender', number: 16 },
    { name: 'R. Doan', position: 'Midfielder', number: 10 },
    { name: 'W. Endo', position: 'Midfielder', number: 6 },
    { name: 'D. Kamada', position: 'Midfielder', number: 15 },
    { name: 'K. Sano', position: 'Midfielder', number: 24 },
    { name: 'A. Tanaka', position: 'Midfielder', number: 7 },
    { name: 'J. Ito', position: 'Attacker', number: 14 },
    { name: 'T. Kubo', position: 'Attacker', number: 8 },
    { name: 'D. Maeda', position: 'Attacker', number: 11 },
    { name: 'Keito Nakamura', position: 'Midfielder', number: 13 },
    { name: 'Y. Suzuki', position: 'Midfielder', number: 17 },
    { name: 'K. Goto', position: 'Attacker', number: 9 },
    { name: 'Koki Ogawa', position: 'Attacker', number: 19 },
    { name: 'K. Shiogai', position: 'Attacker', number: 26 },
    { name: 'A. Ueda', position: 'Attacker', number: 18 },
  ],
  'Sweden': [
    { name: 'V. Johansson', position: 'Goalkeeper', number: 12 },
    { name: 'K. Nordfeldt', position: 'Goalkeeper', number: 23 },
    { name: 'J. Widell Zetterström', position: 'Goalkeeper', number: 1 },
    { name: 'H. Ekdal', position: 'Defender', number: 14 },
    { name: 'G. Gudmundsson', position: 'Midfielder', number: 5 },
    { name: 'I. Hien', position: 'Defender', number: 4 },
    { name: 'G. Lagerbielke', position: 'Defender', number: 2 },
    { name: 'V. Lindelöf', position: 'Defender', number: 3 },
    { name: 'C. Starfelt', position: 'Defender', number: 15 },
    { name: 'H. Johansson', position: 'Midfielder', number: 6 },
    { name: 'E. Smith', position: 'Defender', number: 20 },
    { name: 'E. Stroud', position: 'Midfielder', number: 24 },
    { name: 'D. Svensson', position: 'Defender', number: 8 },
    { name: 'A. Bernhardsson', position: 'Midfielder', number: 21 },
    { name: 'Y. Ayari', position: 'Midfielder', number: 18 },
    { name: 'L. Bergvall', position: 'Midfielder', number: 7 },
    { name: 'B. Nygren', position: 'Attacker', number: 10 },
    { name: 'J. Karlström', position: 'Midfielder', number: 16 },
    { name: 'K. Sema', position: 'Midfielder', number: 13 },
    { name: 'M. Svanberg', position: 'Midfielder', number: 19 },
    { name: 'B. Zeneli', position: 'Midfielder', number: 22 },
    { name: 'T. Ali', position: 'Midfielder', number: 26 },
    { name: 'A. Elanga', position: 'Attacker', number: 11 },
    { name: 'V. Gyökeres', position: 'Attacker', number: 17 },
    { name: 'A. Isak', position: 'Attacker', number: 9 },
    { name: 'G. Nilsson', position: 'Attacker', number: 25 },
  ],
  'Tunisia': [
    { name: 'S. Ben Hsan', position: 'Goalkeeper', number: 22 },
    { name: 'C. Abdelmouhib', position: 'Goalkeeper', number: 1 },
    { name: 'A. Dahmen', position: 'Goalkeeper', number: 16 },
    { name: 'A. Abdi', position: 'Defender', number: 2 },
    { name: 'A. Arous', position: 'Defender', number: 5 },
    { name: 'A. Ben Hmida', position: 'Defender', number: 21 },
    { name: 'D. Bronn', position: 'Defender', number: 6 },
    { name: 'R. Chikhaoui', position: 'Defender', number: 24 },
    { name: 'M. Neffati', position: 'Defender', number: 23 },
    { name: 'O. Rekik', position: 'Defender', number: 4 },
    { name: 'M. Talbi', position: 'Defender', number: 3 },
    { name: 'Y. Valery', position: 'Defender', number: 20 },
    { name: 'M. Ben Ouanes', position: 'Midfielder', number: 12 },
    { name: 'K. Ayari', position: 'Midfielder', number: 14 },
    { name: 'Ismaël Gharbi', position: 'Attacker', number: 11 },
    { name: 'R. Khedira', position: 'Midfielder', number: 13 },
    { name: 'H. Mejbri', position: 'Midfielder', number: 10 },
    { name: 'E. Skhiri', position: 'Midfielder', number: 17 },
    { name: 'A. Ben Slimane', position: 'Midfielder', number: 25 },
    { name: 'H. Mahmoud', position: 'Midfielder', number: 15 },
    { name: 'S. Tounekti', position: 'Attacker', number: 26 },
    { name: 'E. Achouri', position: 'Midfielder', number: 7 },
    { name: 'F. Chaouat', position: 'Attacker', number: 19 },
    { name: 'R. Elloumi', position: 'Attacker', number: 18 },
    { name: 'H. Mastouri', position: 'Attacker', number: 9 },
    { name: 'E. Saad', position: 'Attacker', number: 8 },
  ],
  'Belgium': [
    { name: 'T. Courtois', position: 'Goalkeeper', number: 1 },
    { name: 'S. Lammens', position: 'Goalkeeper', number: 12 },
    { name: 'M. Penders', position: 'Goalkeeper', number: 13 },
    { name: 'T. Castagne', position: 'Defender', number: 21 },
    { name: 'M. De Cuyper', position: 'Defender', number: 5 },
    { name: 'K. De Winter', position: 'Defender', number: 16 },
    { name: 'Z. Debast', position: 'Defender', number: 2 },
    { name: 'B. Mechele', position: 'Defender', number: 4 },
    { name: 'T. Meunier', position: 'Defender', number: 15 },
    { name: 'N. Ngoy', position: 'Defender', number: 25 },
    { name: 'J. Seys', position: 'Defender', number: 18 },
    { name: 'A. Theate', position: 'Defender', number: 3 },
    { name: 'K. De Bruyne', position: 'Midfielder', number: 7 },
    { name: 'A. Onana', position: 'Midfielder', number: 24 },
    { name: 'N. Raskin', position: 'Midfielder', number: 23 },
    { name: 'A. Saelemaekers', position: 'Attacker', number: 22 },
    { name: 'Y. Tielemans', position: 'Midfielder', number: 8 },
    { name: 'D. Moreira', position: 'Attacker', number: 19 },
    { name: 'H. Vanaken', position: 'Midfielder', number: 20 },
    { name: 'A. Witsel', position: 'Midfielder', number: 6 },
    { name: 'J. Doku', position: 'Midfielder', number: 11 },
    { name: 'M. Fernandez-Pardo', position: 'Attacker', number: 26 },
    { name: 'R. Lukaku', position: 'Attacker', number: 9 },
    { name: 'D. Lukebakio', position: 'Attacker', number: 14 },
    { name: 'C. De Ketelaere', position: 'Attacker', number: 17 },
    { name: 'L. Trossard', position: 'Midfielder', number: 10 },
  ],
  'Egypt': [
    { name: 'M. Alaa', position: 'Goalkeeper', number: 26 },
    { name: 'Mohamed El Shenawy', position: 'Goalkeeper', number: 1 },
    { name: 'Mostafa Shobeir', position: 'Goalkeeper', number: 23 },
    { name: 'Al Mahdi Soliman', position: 'Goalkeeper', number: 16 },
    { name: 'Hossam Abdelmaguid', position: 'Defender', number: 4 },
    { name: 'Mohamed Abdelmonem', position: 'Defender', number: 6 },
    { name: 'Ahmed Fatouh', position: 'Defender', number: 13 },
    { name: 'Karim Hafez', position: 'Defender', number: 15 },
    { name: 'Mohamed Hany', position: 'Defender', number: 3 },
    { name: 'Yasser Ibrahim', position: 'Defender', number: 2 },
    { name: 'Rami Rabia', position: 'Defender', number: 5 },
    { name: 'T. Alaa', position: 'Defender', number: 24 },
    { name: 'Emam Ashour', position: 'Midfielder', number: 8 },
    { name: 'Marwan Attia', position: 'Midfielder', number: 19 },
    { name: 'Nabil Emad Dunga', position: 'Midfielder', number: 18 },
    { name: 'Hamdi Fathy', position: 'Defender', number: 14 },
    { name: 'Mohanad Lasheen', position: 'Midfielder', number: 17 },
    { name: 'Mahmoud Saber', position: 'Midfielder', number: 21 },
    { name: 'Mostafa Zico', position: 'Midfielder', number: 11 },
    { name: 'Trézéguet', position: 'Midfielder', number: 7 },
    { name: 'H. Hassan', position: 'Midfielder', number: 12 },
    { name: 'Ahmed Zizo', position: 'Attacker', number: 25 },
    { name: 'H. Abdelkarim', position: 'Attacker', number: 9 },
    { name: 'Ibrahim Adel', position: 'Attacker', number: 20 },
    { name: 'Omar Marmoush', position: 'Attacker', number: 22 },
    { name: 'Mohamed Salah', position: 'Attacker', number: 10 },
  ],
  'Iran': [
    { name: 'A. Beiranvand', position: 'Goalkeeper', number: 1 },
    { name: 'H. Hosseini', position: 'Goalkeeper', number: 22 },
    { name: 'P. Niazmand', position: 'Goalkeeper', number: 12 },
    { name: 'D. Eiri', position: 'Defender', number: 25 },
    { name: 'R. Rezaeian', position: 'Defender', number: 23 },
    { name: 'E. Hajisafi', position: 'Defender', number: 3 },
    { name: 'Saleh Hardani', position: 'Defender', number: 2 },
    { name: 'H. Kanani', position: 'Defender', number: 13 },
    { name: 'S. Khalilzadeh', position: 'Defender', number: 4 },
    { name: 'M. Mohammadi', position: 'Defender', number: 5 },
    { name: 'A. Nemati', position: 'Defender', number: 19 },
    { name: 'A. Yousefi', position: 'Defender', number: 17 },
    { name: 'A. Jahanbakhsh', position: 'Midfielder', number: 7 },
    { name: 'R. Cheshmi', position: 'Midfielder', number: 15 },
    { name: 'S. Ezatolahi', position: 'Midfielder', number: 6 },
    { name: 'S. Ghoddos', position: 'Midfielder', number: 14 },
    { name: 'A. Razzaghinia', position: 'Midfielder', number: 28 },
    { name: 'M. Ghorbani', position: 'Midfielder', number: 11 },
    { name: 'M. Mohebi', position: 'Attacker', number: 8 },
    { name: 'M. Torabi', position: 'Midfielder', number: 16 },
    { name: 'M. Ghaedi', position: 'Attacker', number: 10 },
    { name: 'A. Hosseinzadeh', position: 'Attacker', number: 18 },
    { name: 'A. Alipour', position: 'Attacker', number: 20 },
    { name: 'S. Moghanlou', position: 'Attacker', number: 20 },
    { name: 'D. Eckert Ayensa', position: 'Attacker', number: 24 },
    { name: 'M. Taremi', position: 'Attacker', number: 9 },
  ],
  'New Zealand': [
    { name: 'M. Crocombe', position: 'Goalkeeper', number: 1 },
    { name: 'A. Paulsen', position: 'Goalkeeper', number: 12 },
    { name: 'M. Woud', position: 'Goalkeeper', number: 22 },
    { name: 'Tyler Bindon', position: 'Defender', number: 4 },
    { name: 'M. Boxall', position: 'Defender', number: 5 },
    { name: 'L. Cacace', position: 'Defender', number: 13 },
    { name: 'F. de Vries', position: 'Defender', number: 3 },
    { name: 'C. Elliot', position: 'Defender', number: 24 },
    { name: 'T. Payne', position: 'Defender', number: 2 },
    { name: 'N. Pijnaker', position: 'Defender', number: 15 },
    { name: 'T. Smith', position: 'Defender', number: 26 },
    { name: 'F. Surman', position: 'Defender', number: 16 },
    { name: 'L. Bayliss', position: 'Midfielder', number: 25 },
    { name: 'J. Bell', position: 'Midfielder', number: 6 },
    { name: 'M. Garbett', position: 'Midfielder', number: 7 },
    { name: 'C. McCowatt', position: 'Midfielder', number: 20 },
    { name: 'A. Rufer', position: 'Midfielder', number: 14 },
    { name: 'S. Singh', position: 'Midfielder', number: 10 },
    { name: 'M. Stamenic', position: 'Midfielder', number: 8 },
    { name: 'R. Thomas', position: 'Midfielder', number: 23 },
    { name: 'E. Just', position: 'Midfielder', number: 11 },
    { name: 'B. Old', position: 'Attacker', number: 19 },
    { name: 'K. Barbarouses', position: 'Attacker', number: 17 },
    { name: 'J. Randall', position: 'Attacker', number: 21 },
    { name: 'B. Waine', position: 'Attacker', number: 18 },
    { name: 'C. Wood', position: 'Attacker', number: 9 },
  ],
  'Spain': [
    { name: 'Joan García', position: 'Goalkeeper', number: 13 },
    { name: 'David Raya', position: 'Goalkeeper', number: 1 },
    { name: 'Unai Simón', position: 'Goalkeeper', number: 23 },
    { name: 'Pau Cubarsí Paredes', position: 'Defender', number: 22 },
    { name: 'Marc Cucurella', position: 'Defender', number: 24 },
    { name: 'Eric García', position: 'Defender', number: 4 },
    { name: 'Álex Grimaldo', position: 'Defender', number: 3 },
    { name: 'Aymeric Laporte', position: 'Defender', number: 14 },
    { name: 'Marcos Llorente', position: 'Midfielder', number: 5 },
    { name: 'Pedro Porro', position: 'Defender', number: 12 },
    { name: 'Marc Pubill', position: 'Defender', number: 2 },
    { name: 'Gavi', position: 'Midfielder', number: 9 },
    { name: 'Mikel Merino', position: 'Midfielder', number: 6 },
    { name: 'Pedri', position: 'Midfielder', number: 20 },
    { name: 'Rodri', position: 'Midfielder', number: 16 },
    { name: 'Fabián Ruiz', position: 'Midfielder', number: 8 },
    { name: 'Martín Zubimendi', position: 'Midfielder', number: 18 },
    { name: 'Álex Baena', position: 'Midfielder', number: 15 },
    { name: 'Dani Olmo', position: 'Midfielder', number: 10 },
    { name: 'Borja Iglesias', position: 'Attacker', number: 26 },
    { name: 'Lamine Yamal', position: 'Attacker', number: 19 },
    { name: 'Víctor Muñoz', position: 'Attacker', number: 25 },
    { name: 'Mikel Oyarzabal', position: 'Attacker', number: 21 },
    { name: 'Yeremy Pino', position: 'Midfielder', number: 11 },
    { name: 'Ferran Torres', position: 'Midfielder', number: 7 },
    { name: 'Nico Williams', position: 'Attacker', number: 17 },
  ],
  'Cape Verde': [
    { name: 'Márcio Rosa', position: 'Goalkeeper', number: 12 },
    { name: 'Vózinha', position: 'Goalkeeper', number: 1 },
    { name: 'C. dos Santos', position: 'Goalkeeper', number: 23 },
    { name: 'Diney Borges', position: 'Defender', number: 3 },
    { name: 'Logan Costa', position: 'Defender', number: 5 },
    { name: 'S. Lopes Cabral', position: 'Defender', number: 13 },
    { name: 'Pico', position: 'Defender', number: 4 },
    { name: 'S. Moreira', position: 'Defender', number: 22 },
    { name: 'Wagner Pina', position: 'Defender', number: 24 },
    { name: 'Kelvin Pires', position: 'Defender', number: 25 },
    { name: 'Stopira', position: 'Defender', number: 2 },
    { name: 'Telmo Arcanjo', position: 'Midfielder', number: 18 },
    { name: 'Deroy Duarte', position: 'Midfielder', number: 14 },
    { name: 'L. Duarte', position: 'Midfielder', number: 15 },
    { name: 'João Paulo', position: 'Midfielder', number: 8 },
    { name: 'Kevin Pina', position: 'Midfielder', number: 6 },
    { name: 'Jamiro Monteiro', position: 'Midfielder', number: 10 },
    { name: 'Yannick Semedo', position: 'Midfielder', number: 16 },
    { name: 'Garry Rodrigues', position: 'Midfielder', number: 11 },
    { name: 'Nuno da Costa', position: 'Attacker', number: 21 },
    { name: 'Jovane Cabral', position: 'Attacker', number: 7 },
    { name: 'Willy Semedo', position: 'Midfielder', number: 17 },
    { name: 'Hélio Varela', position: 'Midfielder', number: 26 },
    { name: 'Ryan Mendes', position: 'Midfielder', number: 20 },
    { name: 'Gilson Benchimol', position: 'Attacker', number: 9 },
    { name: 'D. Livramento', position: 'Attacker', number: 19 },
  ],
  'Saudi Arabia': [
    { name: 'Nawaf Al Aqidi', position: 'Goalkeeper', number: 1 },
    { name: 'Ahmed Al Kassar', position: 'Goalkeeper', number: 22 },
    { name: 'Mohammed Al Owais', position: 'Goalkeeper', number: 21 },
    { name: 'Saud Abdulhamid', position: 'Defender', number: 12 },
    { name: 'Mohammed Abu Al Shamat', position: 'Midfielder', number: 26 },
    { name: 'Nawaf Boushal', position: 'Defender', number: 13 },
    { name: 'Abdulelah Al Amri', position: 'Defender', number: 4 },
    { name: 'Moteb Al Harbi', position: 'Defender', number: 24 },
    { name: 'Hassan Kadesh', position: 'Defender', number: 14 },
    { name: 'Ali Lajami', position: 'Defender', number: 3 },
    { name: 'Ali Majrashi', position: 'Defender', number: 2 },
    { name: 'Hassan Tambakti', position: 'Defender', number: 5 },
    { name: 'J. Thakri', position: 'Defender', number: 25 },
    { name: 'Nasser Al Dawsari', position: 'Midfielder', number: 6 },
    { name: 'Mohamed Kanno', position: 'Midfielder', number: 28 },
    { name: 'Ziyad Al Johani', position: 'Midfielder', number: 16 },
    { name: 'Musab Al Juwayr', position: 'Attacker', number: 7 },
    { name: 'Abdullah Al Khaibari', position: 'Midfielder', number: 15 },
    { name: 'Ala Al Haji', position: 'Midfielder', number: 30 },
    { name: 'Khalid Al Ghannam', position: 'Attacker', number: 17 },
    { name: 'Sultan Mandash', position: 'Attacker', number: 27 },
    { name: 'Ayman Yahya', position: 'Attacker', number: 8 },
    { name: 'Feras Al Brikan', position: 'Attacker', number: 9 },
    { name: 'Abdullah Al Hamdan', position: 'Attacker', number: 19 },
    { name: 'Saleh Al Shehri', position: 'Attacker', number: 11 },
    { name: 'Salem Al Dawsari', position: 'Midfielder', number: 10 },
  ],
  'Uruguay': [
    { name: 'S. Mele', position: 'Goalkeeper', number: 12 },
    { name: 'F. Muslera', position: 'Goalkeeper', number: 23 },
    { name: 'S. Rochet', position: 'Goalkeeper', number: 1 },
    { name: 'R. Araújo', position: 'Defender', number: 4 },
    { name: 'S. Bueno', position: 'Defender', number: 24 },
    { name: 'S. Cáceres', position: 'Defender', number: 3 },
    { name: 'J. Giménez', position: 'Defender', number: 2 },
    { name: 'M. Olivera', position: 'Defender', number: 16 },
    { name: 'G. Varela', position: 'Defender', number: 13 },
    { name: 'M. Viña', position: 'Defender', number: 17 },
    { name: 'R. Bentancur', position: 'Midfielder', number: 6 },
    { name: 'E. Martínez', position: 'Midfielder', number: 15 },
    { name: 'J. Sanabria', position: 'Midfielder', number: 25 },
    { name: 'M. Ugarte', position: 'Midfielder', number: 5 },
    { name: 'F. Valverde', position: 'Midfielder', number: 8 },
    { name: 'R. Zalazar', position: 'Midfielder', number: 26 },
    { name: 'G. de Arrascaeta', position: 'Midfielder', number: 10 },
    { name: 'N. de la Cruz', position: 'Midfielder', number: 7 },
    { name: 'M. Araújo', position: 'Midfielder', number: 20 },
    { name: 'A. Canobbio', position: 'Midfielder', number: 14 },
    { name: 'R. Aguirre', position: 'Attacker', number: 19 },
    { name: 'J. Piquerez', position: 'Attacker', number: 22 },
    { name: 'D. Núñez', position: 'Attacker', number: 9 },
    { name: 'F. Pellistri', position: 'Attacker', number: 11 },
    { name: 'B. Rodríguez', position: 'Attacker', number: 18 },
    { name: 'F. Viñas', position: 'Attacker', number: 21 },
  ],
  'France': [
    { name: 'M. Maignan', position: 'Goalkeeper', number: 16 },
    { name: 'R. Risser', position: 'Goalkeeper', number: 23 },
    { name: 'B. Samba', position: 'Goalkeeper', number: 1 },
    { name: 'L. Digne', position: 'Defender', number: 3 },
    { name: 'M. Gusto', position: 'Defender', number: 2 },
    { name: 'L. Hernández', position: 'Defender', number: 21 },
    { name: 'T. Hernández', position: 'Defender', number: 19 },
    { name: 'I. Konaté', position: 'Defender', number: 15 },
    { name: 'J. Koundé', position: 'Defender', number: 5 },
    { name: 'M. Lacroix', position: 'Defender', number: 26 },
    { name: 'W. Saliba', position: 'Defender', number: 17 },
    { name: 'D. Upamecano', position: 'Defender', number: 4 },
    { name: 'R. Cherki', position: 'Midfielder', number: 24 },
    { name: 'N. Kanté', position: 'Midfielder', number: 13 },
    { name: 'M. Koné', position: 'Midfielder', number: 6 },
    { name: 'A. Rabiot', position: 'Midfielder', number: 14 },
    { name: 'A. Tchouaméni', position: 'Midfielder', number: 8 },
    { name: 'W. Zaïre-Emery', position: 'Midfielder', number: 18 },
    { name: 'M. Akliouche', position: 'Midfielder', number: 25 },
    { name: 'B. Barcola', position: 'Attacker', number: 12 },
    { name: 'J. Mateta', position: 'Attacker', number: 22 },
    { name: 'O. Dembélé', position: 'Midfielder', number: 7 },
    { name: 'D. Doué', position: 'Midfielder', number: 20 },
    { name: 'Kylian Mbappé', position: 'Attacker', number: 10 },
    { name: 'M. Thuram', position: 'Midfielder', number: 9 },
    { name: 'M. Olise', position: 'Midfielder', number: 11 },
  ],
  'Senegal': [
    { name: 'M. Diaw', position: 'Goalkeeper', number: 23 },
    { name: 'Y. Diouf', position: 'Goalkeeper', number: 1 },
    { name: 'É. Mendy', position: 'Goalkeeper', number: 16 },
    { name: 'E. Diouf', position: 'Defender', number: 25 },
    { name: 'I. Jakobs', position: 'Midfielder', number: 14 },
    { name: 'K. Koulibaly', position: 'Defender', number: 3 },
    { name: 'A. Mendy', position: 'Defender', number: 24 },
    { name: 'M. Niakhaté', position: 'Defender', number: 19 },
    { name: 'M. Sarr', position: 'Defender', number: 2 },
    { name: 'A. Seck', position: 'Defender', number: 4 },
    { name: 'K. Diatta', position: 'Defender', number: 15 },
    { name: 'L. Camara', position: 'Midfielder', number: 8 },
    { name: 'P. Ciss', position: 'Midfielder', number: 6 },
    { name: 'H. Diarra', position: 'Attacker', number: 21 },
    { name: 'I. Gueye', position: 'Midfielder', number: 5 },
    { name: 'P. Gueye', position: 'Midfielder', number: 26 },
    { name: 'Bara Ndiaye', position: 'Midfielder', number: 27 },
    { name: 'P. Sarr', position: 'Midfielder', number: 17 },
    { name: 'Assane Diao', position: 'Attacker', number: 7 },
    { name: 'B. Dieng', position: 'Attacker', number: 9 },
    { name: 'N. Jackson', position: 'Attacker', number: 11 },
    { name: 'S. Mané', position: 'Attacker', number: 10 },
    { name: 'I. Mbaye', position: 'Attacker', number: 27 },
    { name: 'C. Ndiaye', position: 'Attacker', number: 12 },
    { name: 'I. Ndiaye', position: 'Midfielder', number: 13 },
    { name: 'I. Sarr', position: 'Attacker', number: 18 },
  ],
  'Iraq': [
    { name: 'Ahmed Basil', position: 'Goalkeeper', number: 22 },
    { name: 'Jalal Hassan Hachim', position: 'Goalkeeper', number: 12 },
    { name: 'Fahad Talib', position: 'Goalkeeper', number: 1 },
    { name: 'Hussein Ali', position: 'Defender', number: 3 },
    { name: 'Merchas Doski', position: 'Defender', number: 23 },
    { name: 'Frans Putros', position: 'Defender', number: 26 },
    { name: 'Mustafa Saadoun', position: 'Defender', number: 25 },
    { name: 'Rebin Solaka', position: 'Defender', number: 2 },
    { name: 'Zayed Tahseen', position: 'Defender', number: 4 },
    { name: 'A. Yahya', position: 'Defender', number: 15 },
    { name: 'Munaf Younus', position: 'Defender', number: 6 },
    { name: 'Akam Rahman', position: 'Defender', number: 5 },
    { name: 'Amir Al Ammari', position: 'Midfielder', number: 16 },
    { name: 'Youssef Amyn', position: 'Attacker', number: 7 },
    { name: 'Ibraheem Bayesh', position: 'Midfielder', number: 8 },
    { name: 'Zidane Iqbal', position: 'Midfielder', number: 14 },
    { name: 'Z. Ismaeel', position: 'Midfielder', number: 24 },
    { name: 'A. Sher', position: 'Midfielder', number: 20 },
    { name: 'Kevin Yakob', position: 'Midfielder', number: 19 },
    { name: 'A. Jasim', position: 'Attacker', number: 17 },
    { name: 'Ali Al Hamadi', position: 'Attacker', number: 9 },
    { name: 'M. Farji', position: 'Midfielder', number: 21 },
    { name: 'Aymen Hussein', position: 'Attacker', number: 18 },
    { name: 'Meme', position: 'Attacker', number: 10 },
    { name: 'A. Qasem', position: 'Attacker', number: 11 },
    { name: 'A. Y. Hashim', position: 'Attacker', number: 13 },
  ],
  'Norway': [
    { name: 'Ø. Nyland', position: 'Goalkeeper', number: 1 },
    { name: 'E. Selvik', position: 'Goalkeeper', number: 13 },
    { name: 'S. Tangvik', position: 'Goalkeeper', number: 12 },
    { name: 'K. Ajer', position: 'Defender', number: 3 },
    { name: 'F. Bjørkan', position: 'Defender', number: 15 },
    { name: 'H. Falchener', position: 'Defender', number: 25 },
    { name: 'S. Langås', position: 'Defender', number: 24 },
    { name: 'T. Heggem', position: 'Defender', number: 17 },
    { name: 'L. Østigård', position: 'Defender', number: 4 },
    { name: 'M. Pedersen', position: 'Defender', number: 16 },
    { name: 'D. Møller Wolfe', position: 'Defender', number: 5 },
    { name: 'T. Aasgaard', position: 'Midfielder', number: 19 },
    { name: 'F. Aursnes', position: 'Midfielder', number: 14 },
    { name: 'P. Berg', position: 'Midfielder', number: 6 },
    { name: 'S. Berge', position: 'Midfielder', number: 8 },
    { name: 'Oscar Bobb', position: 'Midfielder', number: 22 },
    { name: 'M. Ødegaard', position: 'Midfielder', number: 10 },
    { name: 'M. Thorsby', position: 'Midfielder', number: 2 },
    { name: 'K. Thorstvedt', position: 'Midfielder', number: 18 },
    { name: 'A. Schjelderup', position: 'Attacker', number: 21 },
    { name: 'J. Hauge', position: 'Midfielder', number: 23 },
    { name: 'E. Haaland', position: 'Attacker', number: 9 },
    { name: 'J. Strand Larsen', position: 'Attacker', number: 11 },
    { name: 'A. Nusa', position: 'Attacker', number: 20 },
    { name: 'A. Sørloth', position: 'Attacker', number: 7 },
    { name: 'J. Ryerson', position: 'Defender', number: 26 },
  ],
  'Argentina': [
    { name: 'E. Martínez', position: 'Goalkeeper', number: 23 },
    { name: 'J. Musso', position: 'Goalkeeper', number: 1 },
    { name: 'G. Rulli', position: 'Goalkeeper', number: 12 },
    { name: 'L. Balerdi', position: 'Defender', number: 2 },
    { name: 'Lisandro Martínez', position: 'Defender', number: 6 },
    { name: 'F. Medina', position: 'Defender', number: 25 },
    { name: 'N. Molina', position: 'Defender', number: 26 },
    { name: 'G. Montiel', position: 'Defender', number: 4 },
    { name: 'N. Otamendi', position: 'Defender', number: 19 },
    { name: 'C. Romero', position: 'Defender', number: 13 },
    { name: 'N. Tagliafico', position: 'Defender', number: 3 },
    { name: 'V. Barco', position: 'Midfielder', number: 8 },
    { name: 'E. Fernández', position: 'Midfielder', number: 24 },
    { name: 'G. Lo Celso', position: 'Midfielder', number: 11 },
    { name: 'A. Mac Allister', position: 'Midfielder', number: 20 },
    { name: 'E. Palacios', position: 'Midfielder', number: 14 },
    { name: 'L. Paredes', position: 'Midfielder', number: 5 },
    { name: 'N. González', position: 'Attacker', number: 15 },
    { name: 'R. De Paul', position: 'Midfielder', number: 7 },
    { name: 'T. Almada', position: 'Attacker', number: 16 },
    { name: 'J. Álvarez', position: 'Attacker', number: 9 },
    { name: 'N. Paz', position: 'Attacker', number: 18 },
    { name: 'J. López', position: 'Attacker', number: 21 },
    { name: 'Lautaro Martínez', position: 'Attacker', number: 22 },
    { name: 'L. Messi', position: 'Attacker', number: 10 },
    { name: 'G. Simeone', position: 'Midfielder', number: 17 },
  ],
  'Algeria': [
    { name: 'O. Benbot', position: 'Goalkeeper', number: 16 },
    { name: 'M. Mastil', position: 'Goalkeeper', number: 1 },
    { name: 'L. Zidane', position: 'Goalkeeper', number: 23 },
    { name: 'A. Abada', position: 'Defender', number: 3 },
    { name: 'R. Aït-Nouri', position: 'Defender', number: 15 },
    { name: 'Z. Belaïd', position: 'Defender', number: 5 },
    { name: 'R. Belghali', position: 'Defender', number: 17 },
    { name: 'R. Bensebaïni', position: 'Defender', number: 21 },
    { name: 'S. Chergui', position: 'Defender', number: 26 },
    { name: 'J. Hadjam', position: 'Defender', number: 13 },
    { name: 'A. Mandi', position: 'Defender', number: 2 },
    { name: 'M. Tougai', position: 'Defender', number: 4 },
    { name: 'H. Aouar', position: 'Midfielder', number: 8 },
    { name: 'N. Bentaleb', position: 'Midfielder', number: 19 },
    { name: 'H. Boudaoui', position: 'Midfielder', number: 14 },
    { name: 'I. Maza', position: 'Midfielder', number: 22 },
    { name: 'Y. Titraoui', position: 'Midfielder', number: 24 },
    { name: 'R. Zerrouki', position: 'Midfielder', number: 6 },
    { name: 'F. Chaïbi', position: 'Midfielder', number: 10 },
    { name: 'M. Amoura', position: 'Attacker', number: 18 },
    { name: 'A. Benbouali', position: 'Attacker', number: 12 },
    { name: 'A. Boulbina', position: 'Attacker', number: 20 },
    { name: 'F. Ghedjemis', position: 'Attacker', number: 25 },
    { name: 'A. Gouiri', position: 'Attacker', number: 9 },
    { name: 'A. Hadj-Moussa', position: 'Attacker', number: 11 },
    { name: 'R. Mahrez', position: 'Attacker', number: 7 },
  ],
  'Austria': [
    { name: 'P. Pentz', position: 'Goalkeeper', number: 13 },
    { name: 'A. Schlager', position: 'Goalkeeper', number: 1 },
    { name: 'F. Wiegele', position: 'Goalkeeper', number: 12 },
    { name: 'D. Affengruber', position: 'Defender', number: 2 },
    { name: 'D. Alaba', position: 'Defender', number: 8 },
    { name: 'K. Danso', position: 'Defender', number: 3 },
    { name: 'M. Friedl', position: 'Defender', number: 23 },
    { name: 'P. Lienhart', position: 'Defender', number: 15 },
    { name: 'P. Mwene', position: 'Defender', number: 16 },
    { name: 'S. Posch', position: 'Defender', number: 5 },
    { name: 'M. Svoboda', position: 'Defender', number: 25 },
    { name: 'C. Baumgartner', position: 'Midfielder', number: 19 },
    { name: 'C. Chukwuemeka', position: 'Midfielder', number: 17 },
    { name: 'F. Grillitsch', position: 'Midfielder', number: 10 },
    { name: 'K. Laimer', position: 'Defender', number: 20 },
    { name: 'A. Prass', position: 'Defender', number: 22 },
    { name: 'M. Sabitzer', position: 'Midfielder', number: 9 },
    { name: 'X. Schlager', position: 'Midfielder', number: 4 },
    { name: 'R. Schmid', position: 'Midfielder', number: 18 },
    { name: 'A. Schöpf', position: 'Midfielder', number: 26 },
    { name: 'N. Seiwald', position: 'Midfielder', number: 6 },
    { name: 'P. Wanner', position: 'Midfielder', number: 24 },
    { name: 'P. Wimmer', position: 'Midfielder', number: 21 },
    { name: 'M. Arnautovic', position: 'Attacker', number: 7 },
    { name: 'M. Gregoritsch', position: 'Midfielder', number: 11 },
    { name: 'S. Kalajdzic', position: 'Attacker', number: 14 },
  ],
  'Jordan': [
    { name: 'Yazid Abu Layla', position: 'Goalkeeper', number: 1 },
    { name: 'Abdallah Al Fakhouri', position: 'Goalkeeper', number: 22 },
    { name: 'Noureddin Zaid', position: 'Goalkeeper', number: 12 },
    { name: 'H. Abu Al Dahab', position: 'Defender', number: 4 },
    { name: 'M. Abu Hasheesh', position: 'Defender', number: 2 },
    { name: 'M. Abualnadi', position: 'Defender', number: 16 },
    { name: 'Yazan Al Arab', position: 'Defender', number: 5 },
    { name: 'Saed Al Rosan', position: 'Defender', number: 19 },
    { name: 'A. Badawi', position: 'Defender', number: 26 },
    { name: 'Abdallah Naseeb', position: 'Defender', number: 3 },
    { name: 'Saleem Obaid', position: 'Defender', number: 17 },
    { name: 'Ehsan Haddad', position: 'Defender', number: 23 },
    { name: 'Mohannad Abu Taha', position: 'Defender', number: 20 },
    { name: 'M. Al Daoud', position: 'Midfielder', number: 25 },
    { name: 'Ibrahim Sa\'deh', position: 'Midfielder', number: 15 },
    { name: 'Nizar Al Rashdan', position: 'Midfielder', number: 21 },
    { name: 'Noor Al Rawabdeh', position: 'Midfielder', number: 8 },
    { name: 'Rajaei Ayed', position: 'Midfielder', number: 14 },
    { name: 'Amer Jamous', position: 'Midfielder', number: 6 },
    { name: 'Mahmoud Al Mardi', position: 'Attacker', number: 13 },
    { name: 'Mohammed Abu Zurayq', position: 'Attacker', number: 7 },
    { name: 'O. Al Fakhouri', position: 'Attacker', number: 11 },
    { name: 'A. Azaizeh', position: 'Attacker', number: 24 },
    { name: 'Ali Olwan', position: 'Attacker', number: 9 },
    { name: 'Ibrahim Sabra', position: 'Attacker', number: 18 },
    { name: 'Mousa Tamari', position: 'Midfielder', number: 10 },
  ],
  'Portugal': [
    { name: 'Diogo Costa', position: 'Goalkeeper', number: 1 },
    { name: 'José Sá', position: 'Goalkeeper', number: 12 },
    { name: 'Rui Silva', position: 'Goalkeeper', number: 22 },
    { name: 'Tomás Araújo', position: 'Defender', number: 4 },
    { name: 'João Cancelo', position: 'Defender', number: 20 },
    { name: 'Diogo Dalot', position: 'Defender', number: 5 },
    { name: 'Rúben Dias', position: 'Defender', number: 3 },
    { name: 'Gonçalo Inácio', position: 'Defender', number: 14 },
    { name: 'Nuno Mendes', position: 'Defender', number: 25 },
    { name: 'Nélson Semedo', position: 'Defender', number: 2 },
    { name: 'Renato Veiga', position: 'Defender', number: 13 },
    { name: 'Samú Costa', position: 'Midfielder', number: 24 },
    { name: 'Bruno Fernandes', position: 'Midfielder', number: 8 },
    { name: 'João Neves', position: 'Midfielder', number: 15 },
    { name: 'Rúben Neves', position: 'Midfielder', number: 21 },
    { name: 'Matheus Nunes', position: 'Midfielder', number: 6 },
    { name: 'Bernardo Silva', position: 'Midfielder', number: 10 },
    { name: 'Vitinha', position: 'Midfielder', number: 23 },
    { name: 'Francisco Conceição', position: 'Midfielder', number: 26 },
    { name: 'Gonçalo Guedes', position: 'Attacker', number: 19 },
    { name: 'João Félix', position: 'Attacker', number: 11 },
    { name: 'Rafael Leão', position: 'Midfielder', number: 17 },
    { name: 'Pedro Neto', position: 'Attacker', number: 18 },
    { name: 'Gonçalo Ramos', position: 'Attacker', number: 9 },
    { name: 'Cristiano Ronaldo', position: 'Attacker', number: 7 },
    { name: 'Trincão', position: 'Attacker', number: 16 },
  ],
  'Congo DR': [
    { name: 'M. Epolo', position: 'Goalkeeper', number: 21 },
    { name: 'T. Fayulu', position: 'Goalkeeper', number: 16 },
    { name: 'L. Mpasi', position: 'Goalkeeper', number: 1 },
    { name: 'D. Batubinsika', position: 'Defender', number: 5 },
    { name: 'G. Kalulu', position: 'Defender', number: 24 },
    { name: 'S. Kapuadi', position: 'Defender', number: 3 },
    { name: 'J. Kayembe', position: 'Defender', number: 12 },
    { name: 'A. Masuaku', position: 'Defender', number: 26 },
    { name: 'C. Mbemba', position: 'Defender', number: 22 },
    { name: 'A. Tuanzebe', position: 'Defender', number: 4 },
    { name: 'A. Wan-Bissaka', position: 'Defender', number: 2 },
    { name: 'E. Kayembe', position: 'Midfielder', number: 25 },
    { name: 'S. Moutoussamy', position: 'Midfielder', number: 8 },
    { name: 'N. Mukau', position: 'Midfielder', number: 6 },
    { name: 'C. Pickel', position: 'Midfielder', number: 18 },
    { name: 'N. Sadiki', position: 'Midfielder', number: 14 },
    { name: 'A. Tshibola', position: 'Midfielder', number: 15 },
    { name: 'N. Mbuku', position: 'Midfielder', number: 7 },
    { name: 'T. Bongonda', position: 'Midfielder', number: 10 },
    { name: 'C. Bakambu', position: 'Attacker', number: 17 },
    { name: 'S. Banza', position: 'Attacker', number: 23 },
    { name: 'B. Cipenga', position: 'Attacker', number: 9 },
    { name: 'M. Elia', position: 'Attacker', number: 13 },
    { name: 'G. Kakuta', position: 'Attacker', number: 11 },
    { name: 'F. Mayele', position: 'Attacker', number: 19 },
    { name: 'Y. Wissa', position: 'Attacker', number: 20 },
  ],
  'Uzbekistan': [
    { name: 'B. Ergashev', position: 'Goalkeeper', number: 16 },
    { name: 'A. Nematov', position: 'Goalkeeper', number: 12 },
    { name: 'U. Yusupov', position: 'Goalkeeper', number: 1 },
    { name: 'K. Alijonov', position: 'Defender', number: 3 },
    { name: 'R. Ashurmatov', position: 'Defender', number: 5 },
    { name: 'U. Eshmurodov', position: 'Defender', number: 15 },
    { name: 'B. Karimov', position: 'Defender', number: 24 },
    { name: 'A. Khusanov', position: 'Defender', number: 2 },
    { name: 'S. Nasrullayev', position: 'Midfielder', number: 13 },
    { name: 'F. Sayfiev', position: 'Defender', number: 4 },
    { name: 'J. Urozov', position: 'Defender', number: 27 },
    { name: 'A. Abdullaev', position: 'Defender', number: 18 },
    { name: 'A. Ulmasaliev', position: 'Defender', number: 25 },
    { name: 'J. Masharipov', position: 'Midfielder', number: 10 },
    { name: 'A. Ganiyev', position: 'Attacker', number: 19 },
    { name: 'J. Iskanderov', position: 'Midfielder', number: 8 },
    { name: 'O. Hamrobekov', position: 'Midfielder', number: 9 },
    { name: 'A. Mozgovoy', position: 'Midfielder', number: 6 },
    { name: 'O. Shukurov', position: 'Midfielder', number: 7 },
    { name: 'A. Fayzullaev', position: 'Attacker', number: 22 },
    { name: 'S. Esanov', position: 'Midfielder', number: 23 },
    { name: 'O. Orunov', position: 'Attacker', number: 11 },
    { name: 'D. Khamdamov', position: 'Midfielder', number: 17 },
    { name: 'A. Amonov', position: 'Attacker', number: 28 },
    { name: 'I. Sergeev', position: 'Attacker', number: 21 },
    { name: 'E. Shomurodov', position: 'Attacker', number: 14 },
  ],
  'Colombia': [
    { name: 'Á. Montero', position: 'Goalkeeper', number: 24 },
    { name: 'D. Ospina', position: 'Goalkeeper', number: 1 },
    { name: 'C. Vargas', position: 'Goalkeeper', number: 12 },
    { name: 'S. Arias', position: 'Defender', number: 4 },
    { name: 'W. Ditta', position: 'Defender', number: 18 },
    { name: 'J. Lucumí', position: 'Defender', number: 3 },
    { name: 'D. Machado', position: 'Defender', number: 22 },
    { name: 'Y. Mina', position: 'Defender', number: 13 },
    { name: 'J. Mojica', position: 'Defender', number: 17 },
    { name: 'D. Muñoz', position: 'Defender', number: 2 },
    { name: 'G. Puerta', position: 'Midfielder', number: 14 },
    { name: 'D. Sánchez', position: 'Defender', number: 23 },
    { name: 'K. Castaño', position: 'Midfielder', number: 5 },
    { name: 'J. Lerma', position: 'Midfielder', number: 16 },
    { name: 'J. Portilla', position: 'Midfielder', number: 15 },
    { name: 'J. Arias', position: 'Midfielder', number: 11 },
    { name: 'J. Carrascal', position: 'Midfielder', number: 8 },
    { name: 'J. Quintero', position: 'Midfielder', number: 20 },
    { name: 'R. Rios', position: 'Midfielder', number: 6 },
    { name: 'J. Rodríguez', position: 'Midfielder', number: 10 },
    { name: 'J. Campaz', position: 'Midfielder', number: 21 },
    { name: 'J. Córdoba', position: 'Attacker', number: 9 },
    { name: 'C. Hernández', position: 'Attacker', number: 19 },
    { name: 'L. Díaz', position: 'Midfielder', number: 7 },
    { name: 'A. Gómez', position: 'Midfielder', number: 26 },
    { name: 'L. Suárez', position: 'Attacker', number: 25 },
  ],
  'England': [
    { name: 'D. Henderson', position: 'Goalkeeper', number: 13 },
    { name: 'J. Pickford', position: 'Goalkeeper', number: 1 },
    { name: 'J. Trafford', position: 'Goalkeeper', number: 23 },
    { name: 'D. Burn', position: 'Defender', number: 15 },
    { name: 'M. Guéhi', position: 'Defender', number: 6 },
    { name: 'R. James', position: 'Defender', number: 24 },
    { name: 'E. Konsa', position: 'Defender', number: 2 },
    { name: 'T. Livramento', position: 'Defender', number: 12 },
    { name: 'N. Oreilly', position: 'Defender', number: 3 },
    { name: 'J. Quansah', position: 'Defender', number: 26 },
    { name: 'D. Spence', position: 'Defender', number: 25 },
    { name: 'J. Stones', position: 'Defender', number: 5 },
    { name: 'E. Anderson', position: 'Midfielder', number: 8 },
    { name: 'J. Bellingham', position: 'Midfielder', number: 10 },
    { name: 'E. Eze', position: 'Midfielder', number: 21 },
    { name: 'J. Henderson', position: 'Midfielder', number: 14 },
    { name: 'K. Mainoo', position: 'Midfielder', number: 16 },
    { name: 'D. Rice', position: 'Midfielder', number: 4 },
    { name: 'M. Rogers', position: 'Midfielder', number: 17 },
    { name: 'A. Gordon', position: 'Attacker', number: 18 },
    { name: 'H. Kane', position: 'Attacker', number: 9 },
    { name: 'N. Madueke', position: 'Attacker', number: 20 },
    { name: 'M. Rashford', position: 'Midfielder', number: 11 },
    { name: 'B. Saka', position: 'Attacker', number: 7 },
    { name: 'I. Toney', position: 'Attacker', number: 22 },
    { name: 'O. Watkins', position: 'Midfielder', number: 19 },
  ],
  'Croatia': [
    { name: 'D. Kotarski', position: 'Goalkeeper', number: 23 },
    { name: 'D. Livakovic', position: 'Goalkeeper', number: 1 },
    { name: 'I. Pandur', position: 'Goalkeeper', number: 12 },
    { name: 'D. Caleta-Car', position: 'Defender', number: 5 },
    { name: 'M. Erlic', position: 'Defender', number: 25 },
    { name: 'J. Gvardiol', position: 'Defender', number: 4 },
    { name: 'M. Pongracic', position: 'Defender', number: 3 },
    { name: 'J. Stanisic', position: 'Defender', number: 2 },
    { name: 'J. Sutalo', position: 'Defender', number: 6 },
    { name: 'L. Vuskovic', position: 'Defender', number: 22 },
    { name: 'M. Baturina', position: 'Midfielder', number: 16 },
    { name: 'T. Fruk', position: 'Midfielder', number: 19 },
    { name: 'K. Jakic', position: 'Midfielder', number: 18 },
    { name: 'M. Kovacic', position: 'Midfielder', number: 8 },
    { name: 'L. Modric', position: 'Midfielder', number: 10 },
    { name: 'N. Moro', position: 'Midfielder', number: 7 },
    { name: 'M. Pasalic', position: 'Midfielder', number: 15 },
    { name: 'L. Sucic', position: 'Midfielder', number: 21 },
    { name: 'P. Sucic', position: 'Midfielder', number: 17 },
    { name: 'N. Vlasic', position: 'Midfielder', number: 13 },
    { name: 'A. Budimir', position: 'Attacker', number: 11 },
    { name: 'A. Kramaric', position: 'Midfielder', number: 9 },
    { name: 'I. Matanovic', position: 'Attacker', number: 20 },
    { name: 'P. Musa', position: 'Attacker', number: 26 },
    { name: 'M. Pasalic', position: 'Midfielder', number: 24 },
    { name: 'I. Perisic', position: 'Midfielder', number: 14 },
  ],
  'Ghana': [
    { name: 'B. Asare', position: 'Goalkeeper', number: 16 },
    { name: 'J. Anang', position: 'Goalkeeper', number: 12 },
    { name: 'L. Zigi', position: 'Goalkeeper', number: 1 },
    { name: 'J. Adjetey', position: 'Defender', number: 4 },
    { name: 'D. Luckassen', position: 'Defender', number: 23 },
    { name: 'G. Mensah', position: 'Defender', number: 14 },
    { name: 'A. Seidu', position: 'Defender', number: 2 },
    { name: 'J. Opoku', position: 'Defender', number: 18 },
    { name: 'K. Peprah Oppong', position: 'Defender', number: 21 },
    { name: 'A. Mumin', position: 'Defender', number: 6 },
    { name: 'M. Senaya', position: 'Defender', number: 26 },
    { name: 'A. Baba', position: 'Defender', number: 17 },
    { name: 'E. Owusu', position: 'Midfielder', number: 15 },
    { name: 'T. Partey', position: 'Midfielder', number: 5 },
    { name: 'K. Sibo', position: 'Midfielder', number: 8 },
    { name: 'Caleb Marfo Yirenkyi', position: 'Midfielder', number: 3 },
    { name: 'A. Semenyo', position: 'Attacker', number: 11 },
    { name: 'A. Boakye', position: 'Midfielder', number: 20 },
    { name: 'A. Fatawu', position: 'Midfielder', number: 7 },
    { name: 'P. Adu', position: 'Midfielder', number: 25 },
    { name: 'B. Thomas-Asante', position: 'Attacker', number: 10 },
    { name: 'J. Ayew', position: 'Attacker', number: 9 },
    { name: 'C. Bonsu Baah', position: 'Attacker', number: 13 },
    { name: 'I. Williams', position: 'Attacker', number: 19 },
    { name: 'E. Nuamah', position: 'Attacker', number: 24 },
    { name: 'K. Sulemana', position: 'Attacker', number: 22 },
  ],
  'Panama': [
    { name: 'L. Mejía', position: 'Goalkeeper', number: 1 },
    { name: 'O. Mosquera', position: 'Goalkeeper', number: 22 },
    { name: 'C. Samudio', position: 'Goalkeeper', number: 12 },
    { name: 'A. Andrade', position: 'Defender', number: 16 },
    { name: 'C. Blackman', position: 'Defender', number: 2 },
    { name: 'J. Córdoba', position: 'Defender', number: 3 },
    { name: 'É. Davis', position: 'Defender', number: 15 },
    { name: 'F. Escobar', position: 'Defender', number: 4 },
    { name: 'E. Fariña', position: 'Defender', number: 5 },
    { name: 'J. Gutiérrez', position: 'Defender', number: 26 },
    { name: 'C. Harvey', position: 'Midfielder', number: 14 },
    { name: 'R. Miller', position: 'Defender', number: 25 },
    { name: 'A. Murillo', position: 'Defender', number: 23 },
    { name: 'J. Ramos', position: 'Defender', number: 13 },
    { name: 'A. Carrasquilla', position: 'Midfielder', number: 8 },
    { name: 'A. Godoy', position: 'Midfielder', number: 20 },
    { name: 'C. Martinez', position: 'Midfielder', number: 6 },
    { name: 'J. Rodríguez', position: 'Midfielder', number: 7 },
    { name: 'Y. Bárcenas', position: 'Midfielder', number: 11 },
    { name: 'I. Díaz', position: 'Midfielder', number: 10 },
    { name: 'A. Quintero', position: 'Midfielder', number: 19 },
    { name: 'C. Yanis', position: 'Midfielder', number: 21 },
    { name: 'J. Fajardo', position: 'Attacker', number: 17 },
    { name: 'A. Londoño', position: 'Midfielder', number: 24 },
    { name: 'T. Rodríguez', position: 'Attacker', number: 9 },
    { name: 'C. Waterman', position: 'Attacker', number: 18 },
  ],
}